### ISSUE TITLE
chiapos/ProofOfSpace 12c9255: "lookup" only uses one GPU for multi-GPU setup, performance anomalies with CUDA_VISIBLE_DEVICES settings

### ISSUE THREAD

**Issue by bladeuserpi** [madMAx43v3r/chia-gigahorse#12]
Hi,

I wanted to test multi-GPU performance with "chiapos/ProofOfSpace lookup".

Actual behaviour: It uses only one GPU.
Even when setting "export CHIAPOS_MAX_CUDA_DEVICES=2" it still uses one GPU.

Expected behaviour: it should use all GPUs by default (or when setting CHIAPOS_MAX_CUDA_DEVICES).

Also there is a performance penalty when using CUDA_VISIBLE_DEVICES for only 1 GPU.
Details see below.

Am I missing something?
```
1) Default settings
===================
[root@c19338cec46c data1]# time ./ProofOfSpace_mmx_12c9255 -r 8 lookup -f plot-k33-c5-2023-02-13-16-22* >x
real	0m22.626s
user	0m7.164s
sys	0m3.371s

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 30%   55C    P8    16W / 125W |    101MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 40%   59C    P2   199W / 225W |    776MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    277826	 C   ./ProofOfSpace_mmx_12c9255         98MiB |
|    1   N/A  N/A    277826	 C   ./ProofOfSpace_mmx_12c9255        774MiB |
+-----------------------------------------------------------------------------+

Result: It uses 3060Ti with 100%, real=22sec. 


2)  export CHIAPOS_MAX_CUDA_DEVICES=2
=====================================
[root@c19338cec46c data1]# time ./ProofOfSpace_mmx_12c9255 -r 8 lookup -f plot-k33-c5-2023-02-13-16-22* >x
real	0m21.611s
user	0m7.369s
sys	0m1.873s

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 30%   60C    P0    37W / 125W |    741MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 40%   63C    P2   201W / 225W |    776MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    277735      C   ./ProofOfSpace_mmx_12c9255        738MiB |
|    1   N/A  N/A    277735      C   ./ProofOfSpace_mmx_12c9255        774MiB |
+-----------------------------------------------------------------------------+

Result: Same as run 1. But in addition it also allocates memory on RTX4000, but does not use GPU%.

3) Reverse CUDA ordering, so it uses RTX4000
============================================
[root@c19338cec46c data1]# export CUDA_VISIBLE_DEVICES=1,0
[root@c19338cec46c data1]# time ./ProofOfSpace_mmx_12c9255 -r 8 lookup -f plot-k33-c5-2023-02-13-16-22*backup >x
real	0m32.347s
user	0m7.612s
sys	0m3.264s

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 30%   66C    P0   121W / 125W |    741MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 40%   48C    P2    67W / 225W |    136MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    278057	 C   ./ProofOfSpace_mmx_12c9255        738MiB |
|    1   N/A  N/A    278057	 C   ./ProofOfSpace_mmx_12c9255        134MiB |
+-----------------------------------------------------------------------------+

Result: Now it uses RTX4000 at 100% GPU, real=32sec. It does not use 3060Ti.

4) Lower performance for CUDA_VISIBLE_DEVICES=1 (which should be equivalent to run (3))
[root@c19338cec46c data1]# export CUDA_VISIBLE_DEVICES=1
[root@c19338cec46c data1]# time ./ProofOfSpace_mmx_12c9255 -r 8 lookup -f plot-k33-c5-2023-02-13-16-22*backup >x
real	0m40.911s
user	0m7.750s
sys	0m1.480s

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 48%   76C    P0    84W / 125W |    741MiB /  8192MiB |     23%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 30%   42C    P0    60W / 225W |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    278404	 C   ./ProofOfSpace_mmx_12c9255        738MiB |
+-----------------------------------------------------------------------------+

Result: Now it uses RTX4000 at 23%, it runs slower with real=40sec

5) Also lower performance for CUDA_VISIBLE_DEVICES=0 (which should be same as run (1))
===========================================
[root@c19338cec46c data1]# export CUDA_VISIBLE_DEVICES=0
[root@c19338cec46c data1]# time ./ProofOfSpace_mmx_12c9255 -r 8 lookup -f plot-k33-c5-2023-02-13-16-22*backup >x
real	0m28.480s
user	0m7.578s
sys	0m3.417s

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 27%   55C    P0    18W / 125W |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 40%   54C    P2   161W / 225W |    776MiB /  8192MiB |     40%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A    278841      C   ./ProofOfSpace_mmx_12c9255        774MiB |
+-----------------------------------------------------------------------------+

Result: Now it uses 3060Ti at 40%, it runs slower with real=28sec.

6) Running without GPU, CPU is 2x Xeon 2698v4
=============================================
export CHIAPOS_MAX_CORES="80"
export CHIAPOS_MAX_CUDA_DEVICES="0"
root@c19338cec46c data1]# time ./ProofOfSpace_mmx_12c9255 -r 80 lookup -f plot-k33-c5-2023-02-13-16-22*backup >x
real	0m55.244s
user	51m12.735s
sys	0m31.537s

top output:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                              
 303755 gputest   20   0   39.0g  24.5g   9024 R  7875   2.4   6:34.19 ProofOfSpace_mm       

Result: GPU is faster than this dual CPU for K33/C5

7)
I am using latest binary as of today:
[root@c19338cec46c data1]# md5sum ProofOfSpace_mmx_12c9255 
201b230da0650ef13f396d920575ad39  ProofOfSpace_mmx_12c9255

**Comment by madMAx43v3r** [comment]
I suspect you're limited by IO latency with k33 C5, it wont touch the second GPU if the first is not maxed out. Try `-r 16` or higher C level.

**Comment by madMAx43v3r** [comment]
Also it prints at the beginning how many GPUs it's using, can you verify that?

**Comment by madMAx43v3r** [comment]
Testing K32 C8 lookup with default settings and `-r 16` on 4x A100:
```
mad@multi-gpu-test-1:~/chia-gigahorse/cuda-plotter/linux/x86_64$ nvidia-smi 
Mon Feb 13 21:33:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0   219W / 400W |   3271MiB / 40960MiB |     52%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   42C    P0   226W / 400W |   3271MiB / 40960MiB |     44%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  Off  | 00000000:00:06.0 Off |                    0 |
| N/A   36C    P0    75W / 400W |   3271MiB / 40960MiB |     37%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   36C    P0    64W / 400W |   3271MiB / 40960MiB |     39%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      6350      C   ./ProofOfSpace                   3266MiB |
|    1   N/A  N/A      6350      C   ./ProofOfSpace                   3266MiB |
|    2   N/A  N/A      6350      C   ./ProofOfSpace                   3266MiB |
|    3   N/A  N/A      6350      C   ./ProofOfSpace                   3266MiB |
+-----------------------------------------------------------------------------+
```
Same with `-r 64` and `CHIAPOS_MAX_CORES=64`:
```
mad@multi-gpu-test-1:~/chia-gigahorse/cuda-plotter/linux/x86_64$ nvidia-smi 
Mon Feb 13 21:35:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0   244W / 400W |   3271MiB / 40960MiB |     91%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   42C    P0   174W / 400W |   3271MiB / 40960MiB |     81%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  Off  | 00000000:00:06.0 Off |                    0 |
| N/A   42C    P0   243W / 400W |   3271MiB / 40960MiB |     81%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   43C    P0   248W / 400W |   3271MiB / 40960MiB |     84%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      6427      C   ./ProofOfSpace                   3266MiB |
|    1   N/A  N/A      6427      C   ./ProofOfSpace                   3266MiB |
|    2   N/A  N/A      6427      C   ./ProofOfSpace                   3266MiB |
|    3   N/A  N/A      6427      C   ./ProofOfSpace                   3266MiB |
+-----------------------------------------------------------------------------+
```
It's not easy keeping 4x A100 busy...

But as you can see it works as expected.

**Comment by madMAx43v3r** [comment]
Now for K32 C6, which is the same workload as your K33 C5, with `-r 64` and `CHIAPOS_MAX_CORES=64`:
```
mad@multi-gpu-test-1:~/chia-gigahorse/cuda-plotter/linux/x86_64$ nvidia-smi 
Mon Feb 13 21:45:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0   247W / 400W |   1185MiB / 40960MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   33C    P0    59W / 400W |   1185MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  Off  | 00000000:00:06.0 Off |                    0 |
| N/A   32C    P0    59W / 400W |   1185MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   35C    P0    63W / 400W |   1185MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      7525      C   ./ProofOfSpace                   1182MiB |
|    1   N/A  N/A      7525      C   ./ProofOfSpace                   1182MiB |
|    2   N/A  N/A      7525      C   ./ProofOfSpace                   1182MiB |
|    3   N/A  N/A      7525      C   ./ProofOfSpace                   1182MiB |
+-----------------------------------------------------------------------------+
```
Same behavior as yours. The workload is just too small.

I can maybe improve this, let me check...

**Comment by madMAx43v3r** [comment]
I think it's working as intended, the 100% in `nvidia-smi` is a bit misleading, it's time based not actual workload based.
If you have a kernel that only uses a single GPU core out of 10000, and it's 100% of the time it counts as 100% load in nvidia-smi.

So in essence, if you want to make good use of beefy GPUs, choose a higher C level ;)

**Comment by bladeuserpi** [comment]
Thanks for investigating this issue, I will test higher C level tomorrow.
Reading your comments I assume it uses multi GPU for a single lookup (quality check/proof),
however in practice I see e.g. 7 plots eligible per 9-second interval. Then it would make sense
to parallelize the  7 proofs over GPUs ?
a) Use all GPU for _one_ proof / then use all for next proof -> current mode 
b) Each GPU takes a single proof /when it finishes it takes the next proof --> embarrasly parallel mode

**Comment by madMAx43v3r** [comment]
Ok hold on, if I randomize device selection it does use all GPUs at full 100% even for K32 C6, not sure what's going on...

a) no that's not how it works
b) that's how it already works

The problem seems to be that I allow two CPU threads to use a single GPU, one for compute and one for download.

**Comment by bladeuserpi** [comment]
Thanks, I confirm the performance is better now: 17 seconds (before it was 22 seconds).

However the faster card is only at 68% performance.
Could this also be improved / brought to 100% ?

```
[root@9fa0eeacbcf3 data1]#  time ./ProofOfSpace_mmx_ce8a3fd -r 8 lookup -f plot-k33-c5-2023-02-13-16-22*backup  >x
real	0m17.698s
user	0m7.537s
sys	0m3.368s


+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 47%   76C    P0   125W / 125W |    741MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 35%   53C    P2   157W / 225W |    776MiB /  8192MiB |     68%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    336968      C   ./ProofOfSpace_mmx_ce8a3fd        738MiB |
|    1   N/A  N/A    336968      C   ./ProofOfSpace_mmx_ce8a3fd        774MiB |
+-----------------------------------------------------------------------------+

md5sum of executable
==================
[root@9fa0eeacbcf3 data1]# md5sum ./ProofOfSpace_mmx_ce8a3fd
a0da4cac8beca37e73a8005637bc4d31  ./ProofOfSpace_mmx_ce8a3fd

**Comment by madMAx43v3r** [comment]
Pretty sure you need more threads, try `-r 16`

**Comment by madMAx43v3r** [comment]
Also verify this at the beginning to make sure:
```
[chiapos] Using 32 / 48 CPU threads
[chiapos] Using 4 / 4 CUDA devices
```

**Comment by bladeuserpi** [comment]
More threads "-r 16" does not help in this case. It is the same result as with -r8.

In previous comment you said you would randomize GPU selection, so if to put
50% of work on slower GPU (rtx4000), other 50% on faster GPU (3060ti), then it would explain this result ?

```
[root@9fa0eeacbcf3 data1]#  time ./ProofOfSpace_mmx_ce8a3fd -r 16 lookup  -f plot-k33-c5-2023-02-13-16-22*backup  >out; head -3 out
real	0m17.044s
user	0m8.047s
sys	0m1.857s
operation: lookup
[chiapos] Using 16 / 80 CPU threads
[chiapos] Using 2 / 2 CUDA devices

top, then type "H" for showing tHreads
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                    
 323480 root      20   0   55584   5772   3728 R   2.9   0.0   6:14.01 top                        
 431519 gputest   20   0   15.4g 331364 107884 S   2.9   0.0   0:00.16 ProofOfSpace_mm            
 431511 gputest   20   0   15.4g 331364 107884 S   2.0   0.0   0:00.17 ProofOfSpace_mm            
 431513 gputest   20   0   15.4g 331364 107884 S   2.0   0.0   0:00.16 ProofOfSpace_mm            
 431514 gputest   20   0   15.4g 331364 107884 R   2.0   0.0   0:00.15 ProofOfSpace_mm            
 431515 gputest   20   0   15.4g 331364 107884 S   2.0   0.0   0:01.78 ProofOfSpace_mm            
 431516 gputest   20   0   15.4g 331364 107884 S   2.0   0.0   0:00.12 ProofOfSpace_mm            
 431517 gputest   20   0   15.4g 331364 107884 S   2.0   0.0   0:00.13 ProofOfSpace_mm            
 431524 gputest   20   0   15.4g 331364 107884 S   2.0   0.0   0:00.11 ProofOfSpace_mm            
  24270 root      20   0  531016  68044  46788 S   1.0   0.0   3:22.44 tuned                      
 431509 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.16 ProofOfSpace_mm            
 431510 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.14 ProofOfSpace_mm            
 431512 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.12 ProofOfSpace_mm            
 431518 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.15 ProofOfSpace_mm            
 431520 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.14 ProofOfSpace_mm            
 431521 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.16 ProofOfSpace_mm            
 431522 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.15 ProofOfSpace_mm            
 431523 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.15 ProofOfSpace_mm            
 431538 gputest   20   0   15.4g 331364 107884 S   1.0   0.0   0:00.01 cuda-EvtHandlr             
 431527 root      20   0       0      0      0 S   1.0   0.0   0:00.21 nv_queue           

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 46%   75C    P0   124W / 125W |    741MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 40%   54C    P2   157W / 225W |    776MiB /  8192MiB |     58%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    431708      C   ./ProofOfSpace_mmx_ce8a3fd        738MiB |
|    1   N/A  N/A    431708      C   ./ProofOfSpace_mmx_ce8a3fd        774MiB |
+-----------------------------------------------------------------------------+

**Comment by bladeuserpi** [comment]
To make sure this is not caused by some other (bandwidth etc) bottleneck
I am running two separate processes simultaneously, each with CHIAPOS_MAX_CUDA_DEVICES=1.

Result: Both GPU are used at 100%. The real time is the same as when
I run not simultaneously. So this test does not show a bottleneck.

RTX4000: real=31s, that is 32.3 lookups-per-second
3060ti: real=20s, that is 50 lookups-per-second

When combining it should be 50+32.3 = 82.3 lookups-per-second
That would take 12.15 seconds for 1000 lookups when using both GPU at 100%.
Currently is takes 17 seconds.

```
1a)
root@9fa0eeacbcf3 data1]# export |grep CUDA
declare -x CHIAPOS_MAX_CUDA_DEVICES="1"
declare -x CUDA_VISIBLE_DEVICES="1,0"
[root@9fa0eeacbcf3 data1]# date; time ./ProofOfSpace_mmx_ce8a3fd -r 16 lookup  -f plot-k33-c5-2023-02-13-16-22*backup  >out; head -3 out
Tue Feb 14 08:02:09 UTC 2023

real	0m31.275s
user	0m7.997s
sys	0m1.625s
operation: lookup
[chiapos] Using 16 / 80 CPU threads
[chiapos] Using 1 / 2 CUDA devices


1b)
root@9fa0eeacbcf3 data1]# export|grep CUDA
declare -x CHIAPOS_MAX_CUDA_DEVICES="1"
[root@9fa0eeacbcf3 data1]# date; time ./ProofOfSpace_mmx_ce8a3fd -r 16 lookup  -f plot-k33-c5-2023-02-13-16-22*backup  >out; head -3 out
Tue Feb 14 08:02:15 UTC 2023

real	0m20.567s
user	0m8.008s
sys	0m1.303s
operation: lookup
[chiapos] Using 16 / 80 CPU threads
[chiapos] Using 1 / 2 CUDA devices


+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 30%   65C    P0   123W / 125W |    741MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 40%   53C    P2   195W / 225W |    776MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    435171      C   ./ProofOfSpace_mmx_ce8a3fd        738MiB |
|    1   N/A  N/A    435207      C   ./ProofOfSpace_mmx_ce8a3fd        774MiB |  Separate Processes
+-----------------------------------------------------------------------------+

**Comment by madMAx43v3r** [comment]
> In previous comment you said you would randomize GPU selection, so if to put
50% of work on slower GPU (rtx4000), other 50% on faster GPU (3060ti), then it would explain this result ?

It still checks if a GPU is already busy, and tries to find another one which is idle. Something strange is still going on, I need to debug it further...

**Comment by madMAx43v3r** [comment]
Should be fixed now, latest `linux/x64_64/ProofOfSpace`

**Comment by bladeuserpi** [comment]
I confirm the new version shows further improvement.

- New version 70d2cd5: real = 14.7 seconds
- previous version ce8a3fd: real= 17.0 seconds

That is 68 lookups-per-second for K33/C5 (combined RTX4000+3060Ti).

It still shows about 85% GPU usage, so there might
be some further potential improvement.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 30%   51C    P0   117W / 125W |   1540MiB /  8192MiB |     85%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 30%   57C    P2   181W / 225W |    782MiB /  8192MiB |     86%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    437025	 C   chia_harvester                    738MiB |
|    0   N/A  N/A    438323	 G   /usr/libexec/Xorg                  38MiB |
|    0   N/A  N/A    438613	 G   /usr/bin/gnome-shell               21MiB |
|    0   N/A  N/A    620529	 C   ./ProofOfSpace_mmx_70d2cd5        738MiB |
|    1   N/A  N/A    438323      G   /usr/libexec/Xorg                   4MiB |
|    1   N/A  N/A    620529	 C   ./ProofOfSpace_mmx_70d2cd5        774MiB |
+-----------------------------------------------------------------------------+	

The performance on this machine is the same for 8,6,32 threads.

root@0b6dfd419284 data1]# time ./ProofOfSpace_mmx_70d2cd5 -r 8 lookup  -f plot-k33-c5-2023-02-13-16-22*backup  >out; head -3 out

real	0m14.705s
user	0m8.061s
sys	0m1.697s
operation: lookup
[chiapos] Using 64 / 80 CPU threads
[chiapos] Using 2 / 2 CUDA devices
[root@0b6dfd419284 data1]# time ./ProofOfSpace_mmx_70d2cd5 -r 16 lookup  -f plot-k33-c5-2023-02-13-16-22*backup  >out; head -3 out

real	0m14.753s
user	0m8.395s
sys	0m1.667s
operation: lookup
[chiapos] Using 64 / 80 CPU threads
[chiapos] Using 2 / 2 CUDA devices
[root@0b6dfd419284 data1]# time ./ProofOfSpace_mmx_70d2cd5 -r 32 lookup  -f plot-k33-c5-2023-02-13-16-22*backup  >out; head -3 out

real	0m14.774s
user	0m9.466s
sys	0m1.701s
operation: lookup
[chiapos] Using 64 / 80 CPU threads
[chiapos] Using 2 / 2 CUDA devices

**Comment by madMAx43v3r** [comment]
The 85% might be due to C5, it's just not a lot of work for the GPUs...

**Comment by madMAx43v3r** [comment]
Ok there was another issue in the fix itself, try latest linux ProofOfSpace now. should be 100% on both GPUs.

**Comment by bladeuserpi** [comment]
Thanks, it works perfectly now.

The real time is reduced by another 2.3 seconds (from 15.6 to 13.3)
``` 
1)previous version
root@c7fe6d723cb5 data1]# time ./ProofOfSpace_mmx_70d2cd5 -r 16 lookup  -f plot-k33-c5-2023-02-13-16-22*backup  >out; head -3 out
real    0m15.659s
user    0m8.228s
sys     0m1.832s
operation: lookup
[chiapos] Using 16 / 80 CPU threads
[chiapos] Using 2 / 2 CUDA devices

Side-Note: Today I see +/- seconds time variation for the old version (e.g. previous comment showed 14.7s)

2)New version
[root@c7fe6d723cb5 data1]# time ./ProofOfSpace_mmx_c186dd2 -r 16 lookup  -f plot-k33-c5-2023-02-13-16-22*backup  >out; head -3 out
real    0m13.312s
user    0m7.973s
sys     0m1.769s
operation: lookup
[chiapos] Using 16 / 80 CPU threads
[chiapos] Using 2 / 2 CUDA devices

This also show performance variation from run to run:
e.g. real       0m14.767s


i+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     Off  | 00000000:04:00.0 Off |                  N/A |
| 39%   72C    P0   123W / 125W |    741MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 39%   55C    P2   198W / 225W |    776MiB /  8192MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     80324      C   ./ProofOfSpace_mmx_c186dd2        738MiB |
|    1   N/A  N/A     80324      C   ./ProofOfSpace_mmx_c186dd2        774MiB |
+-----------------------------------------------------------------------------+

**Comment by bladeuserpi** [comment]
Does this improvement also needs porting in harvester (1.6.2-giga4)?
Or does harvester use different code path?

**Comment by madMAx43v3r** [comment]
I need to update the binaries, already testing the new version internally.

**Comment by madMAx43v3r** [comment]
See latest release
